// Builds the Splitdesk logo from one source of truth.
// Mark: a coin cut into three shares (40 / 35 / 25), the accent share pulled out.
// Wordmark: "Splitdesk" in Mozilla Text 600, outlined to paths with opentype.js.
// Outputs: src/components/brand/logoData.ts, public/brand/logo.svg, public/favicon.svg,
//          public/brand/logo-500.png, public/brand/logo-500-transparent.png
import fs from 'node:fs'
import path from 'node:path'
import opentype from 'opentype.js'
import { Resvg } from '@resvg/resvg-js'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const fontFile = path.join(root, 'node_modules/@fontsource/mozilla-text/files/mozilla-text-latin-600-normal.woff')

// Palette (same values as tailwind.config.js tokens)
const INK = '#17181A'
const ACCENT = '#B6F03C'
const PAPER = '#F4F5F1'
const BRAND_BG = '#EDF0E8'

const r2 = (n) => Math.round(n * 100) / 100

// ---- Mark (viewBox 0 0 40 40) ----
function wedge(cx, cy, r, a0, a1, pull) {
  const mid = ((a0 + a1) / 2) * (Math.PI / 180)
  const ox = Math.cos(mid) * pull
  const oy = Math.sin(mid) * pull
  const p = (a) => {
    const t = a * (Math.PI / 180)
    return [r2(cx + ox + Math.cos(t) * r), r2(cy + oy + Math.sin(t) * r)]
  }
  const [x0, y0] = p(a0)
  const [x1, y1] = p(a1)
  const large = a1 - a0 > 180 ? 1 : 0
  return `M${r2(cx + ox)} ${r2(cy + oy)}L${x0} ${y0}A${r} ${r} 0 ${large} 1 ${x1} ${y1}Z`
}
// angles start at the top (-90deg) and run clockwise
const markWedges = [
  { d: wedge(19, 21, 16, -90, 54, 1.2), role: 'ink' }, // 40%
  { d: wedge(19, 21, 16, 54, 180, 1.2), role: 'ink' }, // 35%
  { d: wedge(19, 21, 16, 180, 270, 3.6), role: 'accent' }, // 25%, pulled out
]

// ---- Wordmark ----
const font = opentype.parse(fs.readFileSync(fontFile).buffer.slice(0))
const TEXT = 'Splitdesk'
const FS = 100
const tracking = -0.01 * FS
let x = 0
const glyphPaths = []
for (const g of font.stringToGlyphs(TEXT)) {
  const p = g.getPath(x, 0, FS)
  glyphPaths.push(p.toPathData(2))
  x += (g.advanceWidth / font.unitsPerEm) * FS + tracking
}
const bb = (() => {
  const full = new opentype.Path()
  let xx = 0
  for (const g of font.stringToGlyphs(TEXT)) {
    full.extend(g.getPath(xx, 0, FS))
    xx += (g.advanceWidth / font.unitsPerEm) * FS + tracking
  }
  return full.getBoundingBox()
})()
const wordW = bb.x2 - bb.x1
const wordH = bb.y2 - bb.y1

// Lockup: 145 x 40 (header ratio of the reference box). Mark 40, gap 8, word fills the rest.
const LOCK_W = 145
const LOCK_H = 40
const wordBoxW = LOCK_W - 48
const s = wordBoxW / wordW
const wordDrawH = wordH * s
const ty = (LOCK_H - wordDrawH) / 2 - bb.y1 * s
const tx = 48 - bb.x1 * s
const wordTransform = `translate(${r2(tx)} ${r2(ty)}) scale(${r2(s * 1000) / 1000})`
const wordPath = glyphPaths.join('')

const markSvg = (ink, accent) =>
  markWedges.map((w) => `<path d="${w.d}" fill="${w.role === 'accent' ? accent : ink}"/>`).join('')

// ---- Write TS data for the React components ----
const ts = `// Generated by scripts/build-logo.mjs. Do not edit by hand.
export const LOGO_VIEWBOX = '0 0 ${LOCK_W} ${LOCK_H}'
export const MARK_VIEWBOX = '0 0 40 40'
export const MARK_WEDGES: { d: string; role: 'ink' | 'accent' }[] = ${JSON.stringify(markWedges)}
export const WORDMARK_TRANSFORM = '${wordTransform}'
export const WORDMARK_PATH = '${wordPath}'
`
fs.mkdirSync(path.join(root, 'src/components/brand'), { recursive: true })
fs.writeFileSync(path.join(root, 'src/components/brand/logoData.ts'), ts)

// ---- Standalone SVGs ----
const lockupSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${LOCK_W} ${LOCK_H}" width="${LOCK_W * 4}" height="${LOCK_H * 4}"><title>Splitdesk</title>${markSvg(INK, ACCENT)}<path transform="${wordTransform}" d="${wordPath}" fill="${INK}"/></svg>`
fs.mkdirSync(path.join(root, 'public/brand'), { recursive: true })
fs.writeFileSync(path.join(root, 'public/brand/logo.svg'), lockupSvg)

const lockupDark = lockupSvg.replaceAll(`fill="${INK}"`, `fill="${PAPER}"`)
fs.writeFileSync(path.join(root, 'public/brand/logo-dark.svg'), lockupDark)

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><style>.i{fill:${INK}}@media (prefers-color-scheme:dark){.i{fill:${PAPER}}}</style>${markWedges
  .map((w) => (w.role === 'accent' ? `<path d="${w.d}" fill="${ACCENT}"/>` : `<path class="i" d="${w.d}"/>`))
  .join('')}</svg>`
fs.writeFileSync(path.join(root, 'public/favicon.svg'), favicon)

// ---- 500x500 PNG exports: lockup centred with ~12% padding ----
function squareSvg(bg) {
  const pad = 500 * 0.12
  const w = 500 - pad * 2
  const k = w / LOCK_W
  const h = LOCK_H * k
  const oy = (500 - h) / 2
  return `<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500">${
    bg ? `<rect width="500" height="500" fill="${bg}"/>` : ''
  }<g transform="translate(${pad} ${r2(oy)}) scale(${r2(k * 1000) / 1000})">${markSvg(INK, ACCENT)}<path transform="${wordTransform}" d="${wordPath}" fill="${INK}"/></g></svg>`
}
for (const [file, bg] of [
  ['logo-500.png', BRAND_BG],
  ['logo-500-transparent.png', null],
]) {
  const png = new Resvg(squareSvg(bg), { fitTo: { mode: 'original' }, background: bg ? undefined : 'rgba(0,0,0,0)' })
    .render()
    .asPng()
  fs.writeFileSync(path.join(root, 'public/brand', file), png)
}
console.log('logo built', { wordW: r2(wordW), scale: r2(s), lockup: `${LOCK_W}x${LOCK_H}` })
